### PR TITLE
`KAS_REPO_REF_DIR` bug-fix on kas-container.sh

### PR DESCRIPTION
**Pull request by rotem443**

### CODE REVIEW

**Comment by rotem443** [comment]
I hope that I'm not missing anything, but I have tried for a couple of hours to use KAS_REPO_REF_DIR with kas-container without success (while it's worked perfectly using kas without containers).

This little fix solve the issue for me

**Comment by jan-kiszka** [comment]
Good catch! Seems like no one stressed this so far - since day 1...

Please check https://github.com/siemens/kas/blob/master/CONTRIBUTING.md for the formal process. At least we would need the signed-off to certify DCO.

**Comment by rotem443** [comment]
Thanks! sorry for missing out on the sign-off process, let me know if this is ok now

**Comment by jan-kiszka** [comment]
OK, now bonus for a good patch description:

```
kas-container: Fix mounting of KAS_REPO_REF_DIR into container

Some words, how this was broken, the seen effect.

Signed-off-by: ...
```

And also bonus for rebasing your queue to carry only the final commit, not the history (git rebase -i master... / git commit --ammend / git push -f ...). This is not critical here as I would send the commit to the list first (unless you do) and also merge manually. But other projects that do take PRs directly may appreciate such style.

**Comment by jan-kiszka** [comment]
Almost: There are still 2 commits in your branch. If you do `git rebase -i HEAD~2`, you can mark the second commit as 'squash' and then edit the combined commit log when being asked to so that it carries both the proper subject as first line and the commit message with signed-off. Force-push that single commit, and I can pick it up.

**Comment by rotem443** [comment]
Thanks for all the details! appreciate that. It seems good now

**Comment by jan-kiszka** [comment]
Thanks, sent to the mailing list and merged into next.

**Pull request closed without merging**
